### ISSUE TITLE
[FEATURE] Multi-tenancy configuration

### ISSUE THREAD

**Issue by akennealy** [opensearch-project/terraform-provider-opensearch#104]
### Is your feature request related to a problem?
I don't think I can use this provider to configure multi-tenancy so I have to manually apply the configurations in the Dashboard ui.

### What solution would you like?
I would like to use this provider to configure Multi-tenancy. i.e. enable or disable tenancy / Global / private tenants, Set default tenant.

### What alternatives have you considered?
Script managing this configuration or just stick with manual steps to apply.

### Do you have any additional context?
This could be a more broader feature request to allow configuring cluster security. I search for this request in issues, but haven't found anything.

**Comment by peterzhuamazon** [comment]
Hi @akennealy ,

We currently do not have this function right now.
Are you willing to contribute this feature?
Would love to discuss and potentially a PR.

cc: @prudhvigodithi 

Thanks.

**Comment by spacez320** [comment]
@peterzhuamazon I would be willing to discuss a contributing a PR. Or would you like me to just propose something?

**Comment by prudhvigodithi** [comment]
Hey @spacez320, I'm also open for discussion and would love to listen to your proposal. Thanks 
Adding @bbarani @rblcoder

**Comment by spacez320** [comment]
Sure, thanks @prudhvigodithi . What form of proposal would you like? I have an example of a modification for a specific resource here: https://github.com/opensearch-project/terraform-provider-opensearch/issues/97

I could expand on that to detail all proposed structural changes? Or would you like something more in-depth? Or are you looking for an MR?

Feel free to redirect me to a contributor guide if I should be reading that first.

**Comment by PhilippReinke** [comment]
Hello @peterzhuamazon,

I created a PR (https://github.com/opensearch-project/terraform-provider-opensearch/pull/184) that adds a `tenant_name` argument to the `opensearch_dashboard_object` resource. I tested it with a local OpenSearch deployment and it works. Also, I checked other resources but I don't think they are affected by the multi-tenancy.

Feel free to contact me.

Best wishes
Philipp
