### ISSUE TITLE
Improved documentation around argument default values and basic auth example

### ISSUE THREAD

**Issue by Sovietaced** [opensearch-project/terraform-provider-opensearch#107]
It was surprisingly challenging for me to get going with basic auth. The default values of the arguments are not configured and it was not clear that I would have to explicitly disabling request signing in order to get basic auth to work (was receiving 403s).

**Comment by peterzhuamazon** [comment]
[Triage] Adding @prudhvigodithi to get more information on this.

**Comment by prudhvigodithi** [comment]
Hey @Sovietaced thanks for the feedback, can you please open a PR to fix this?
Thank you

**Comment by Sovietaced** [comment]
> Hey @Sovietaced thanks for the feedback, can you please open a PR to fix this?
> 
> Thank you

Yeah sure. Gimme a week.

**Comment by Sovietaced** [comment]
Given that this project uses `terraform-plugin-docs` to manage its documentation, it appears that the behavior to document the default value is not yet supported unfortunately. https://github.com/hashicorp/terraform-plugin-docs/issues/65

Feels absurd to me that the issue has been laying around for 2 years so I'll just work on adding a basic auth example :(

**Comment by Sovietaced** [comment]
Ready for review: https://github.com/opensearch-project/terraform-provider-opensearch/pull/114

**Comment by prudhvigodithi** [comment]
Thanks @Sovietaced I have assigned this issue to you.
