### ISSUE TITLE
[BUG] Few of the examples mentioned against the terraform resources are incorrect

### ISSUE THREAD

**Issue by premkirank** [opensearch-project/terraform-provider-opensearch#111]
### What is the bug?
- Few of the examples provided against terraform resources like below, have some issues when we try to provision them using ```terraform apply```
- e.g opensearch_index - https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/index
- Need to cross verify if examples mentioned against any other resources also have some issues and fix them

### How can one reproduce the bug?
- On your local file system, try to provision the resource using ```terraform apply``` and see if it is returning any errors related to that
- e.g opensearch_index
<img width="1668" alt="image" src="https://github.com/opensearch-project/terraform-provider-opensearch/assets/126944405/07d6c0d3-d6a5-415f-8fc9-4a1369526643">

### What is the expected behavior?
- Examples should work fine and provision the resource as mentioned in the docs

**Comment by peterzhuamazon** [comment]
[Triage] @premkirank would you mind raise a PR for this issue?
Thanks.

**Comment by prudhvigodithi** [comment]
Thanks @premkirank, We might need to run https://github.com/hashicorp/terraform-plugin-docs and test the generated documents, @premkirank what ever you mentioned in your description is coming from https://github.com/opensearch-project/terraform-provider-opensearch/blob/main/provider/resource_opensearch_index_test.go, can you please take a look to fix this?
Thank you

**Comment by premkirank** [comment]
@prudhvigodithi I tested the resource examples against the latest provider i.e. 2.1.0 (https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs) and noticed that the examples mentioned against the below resources failed due to various reasons like variables not being found etc

- opensearch_anomaly_detection
- opensearch_dashboard_alert (resource not supported)
- opensearch_dashboard_object
- opensearch_data_stream
- opensearch_destination (resource not supported)
- opensearch_ism_policy
- opensearch_monitor
- opensearch_role
- opensearch_snapshot_repository
- opensearch_user
- opensearch_index_test (PR provided above)
- opensearch_index_template (PR provided above)

Also, do I need to create a separate issue to see if we can autogenerate examples for resources?
