### ISSUE TITLE
[BUG]Not able to add provider with data opensearch_host

### ISSUE THREAD

**Issue by sangauppe12** [opensearch-project/terraform-provider-opensearch#132]
data "opensearch_host" "test" {
  active = true
}

I get the error being - Error: HEAD healthcheck failed: This is usually due to network or permission issues. The underlying error isn't accessible, please debug by disabling healthchecks.

**Comment by jordarlu** [comment]
@prudhvigodithi @phillbaker , would you please have a look and give your comments, thanks !!

**Comment by EmilieDel** [comment]
Is there any updates about this ?

**Comment by rblcoder** [comment]
@EmilieDel Could you please share your OpenSearch provider configuration?

**Comment by rblcoder** [comment]
@EmilieDel The following Terraform code works for me

```
terraform {
  required_providers {
    opensearch = {
      source = "opensearch-project/opensearch"
      version = "2.2.1"
    }
  }
}

provider "opensearch" {
  url = "https://localhost:9200"
  username          = "admin"
  password          = "myStrongPassword123@456"

  version_ping_timeout = "10"
  healthcheck = "false"
  insecure = "true"

}


data "opensearch_host" "test" {
  active = true
}

```

**Comment by prudhvigodithi** [comment]
Thanks @rblcoder, @EmilieDel and @sangauppe12 closing this issue, please feel free to re-open or add a comment if required.
Thank you
