### ISSUE TITLE
[FEATURE] Support for readonly flag in `opensearch_snapshot_repository` resource

### ISSUE THREAD

**Issue by shmokmt** [opensearch-project/terraform-provider-opensearch#143]
### Is your feature request related to a problem?

During the migration of an OpenSearch cluster, preventing write operations on the destination OpenSearch can avoid accidents.

### What solution would you like?

I hope readonly flag in `opensearch_snapshot_repository` resource like below.

```
# Create a snapshot repository
resource "opensearch_snapshot_repository" "repo" {
  name = "es-index-backups"
  type = "s3"
  settings = {
    bucket   = "es-index-backups"
    region   = "us-east-1"
    role_arn = "arn:aws:iam::123456789012:role/MyRole"
    readonly = true
  }
}
```

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
* API docs: https://opensearch.org/docs/1.0/opensearch/snapshot-restore/

**Comment by prudhvigodithi** [comment]
[Triage]
Hey @shmokmt I assume you are looking for the following when `readonly = true` is added
```
  "index_settings": {
    "index.blocks.read_only": false
  },
 ```
 
This snapshot feature was added from PR https://github.com/opensearch-project/terraform-provider-opensearch/pull/125, can you please take a look and see if you can contribute ?
 
Thanks 
 Adding @duboisph @rblcoder @bbarani

**Comment by duboisph** [comment]
This request is regarding the `opensearch_snapshot_repository` registering, not Snapshot Management feature added in #125.

That said, [looking at the `opensearch_snapshot_repository` code, this should already work out of the box](https://github.com/opensearch-project/terraform-provider-opensearch/blob/main/provider/resource_opensearch_snapshot_repository.go#L29). The `settings` map is passed completely to the API.

You can use all settings as allowed by the API, docs: https://opensearch.org/docs/latest/api-reference/snapshots/create-repository/

@shmokmt Have you tried this and isn't it working?

**Comment by shmokmt** [comment]
I'm sorry. It seems I was mistaken.
It worked fine.
