### ISSUE TITLE
There is no Notification Channels creation resource in 2.x.x versions, but there is in 1.0.0

### ISSUE THREAD

**Issue by kolesaev** [opensearch-project/terraform-provider-opensearch#149]
### Is your feature request related to a problem?
While we create monitor we need to assign a notification channel. Since we want to implement all the related configs via terraform we don't want to create additional objects inside a cluster manually, but there is no ability with provider version >= 2.0.0

### What solution would you like?
Develop a resource which creates a Notification Channel

### What alternatives have you considered?
Develop a datasource which provides us headers for making an own http-request via terraform/http provider. This would be an awesome solution to implement it for making any http requests to our clusters and would be nice if both, main and alternative solutions, are implemented

### Do you have any additional context?
-

**Comment by kolesaev** [comment]
My bad. I found it called opensearch_channel_configuration. Testing

**Comment by prudhvigodithi** [comment]
Closing this issue, thanks for the contribution @Vonter.
@kolesaev please re-open if required.
