### ISSUE TITLE
[BUG] invalid character 'A' looking for beginning of value

### ISSUE THREAD

**Issue by nikki603** [opensearch-project/terraform-provider-opensearch#169]
### What is the bug?
`terraform apply` returns 
```
│ Error: invalid character 'A' looking for beginning of value
│ 
│   with opensearch_index.index1,
│   on opensearch.tf line 1, in resource "opensearch_index" "index1":
│    1: resource "opensearch_index" "index1" {
```

### How can one reproduce the bug?

```
resource "opensearch_index" "index1" {
  name             = "index1"
  index_knn        = true
  default_pipeline = "my-pipeline-id"
  mappings         = <<EOF
{
    "properties": {
      "entity_name_v": {
        "type": "knn_vector",
        "dimension": 384,
        "method": {
          "name": "hnsw",
          "engine": "lucene",
          "space_type": "cosinesimil"
        }
      },
      "entity_name": {
        "type": "text" 
      }
    }
  }
EOF
}
```

Fails with this error when the provider is using the custom domain URL.
```
provider "opensearch" {
  url         = "https://search.mydomain.com"
  healthcheck = false
}
```
This custom domain is a CNAME record in Route53 with value of the AWS provided domain URL.

It does not fail when using the AWS provided domain URL.
```
provider "opensearch" {
  url         = "https://my-domain.us-east-1.es.amazonaws.com"
  healthcheck = false
}
```

`terraform apply`

### What is the expected behavior?
index1 created successfully

### What is your host/environment?
hashicorp/terraform:1.6.6 Docker container OR MacOS 14.1 (23B2073)
opensearch-project/opensearch provider 2.2.0
AWS OpenSearch version OpenSearch_2_11_R20231113-P4 (latest)

**Comment by rblcoder** [comment]
@nikki603 Is custom endpoint configured? https://docs.aws.amazon.com/opensearch-service/latest/developerguide/customendpoint.html
![opensearch-custom-domain](https://github.com/opensearch-project/terraform-provider-opensearch/assets/35212670/06d0ab6b-55ce-4417-8309-aa1a6268af79)

**Comment by nikki603** [comment]
@rblcoder Yes it's configured. I confirmed the custom URL works various ways like in browser to access the Dashboard, Postman requests, and Logstash output plugin.
<img width="361" alt="Screenshot 2024-03-21 at 9 30 42 AM" src="https://github.com/opensearch-project/terraform-provider-opensearch/assets/5578773/3de0d103-929c-45ed-b30b-46da6df4a4bd">

**Comment by rblcoder** [comment]
@nikki603 Are you able to do a curl from the command line using the custom url?

**Comment by nikki603** [comment]
@rblcoder I still get the same error

![Screenshot 2024-03-21 at 6 44 46 PM](https://github.com/opensearch-project/terraform-provider-opensearch/assets/5578773/ab8f9a04-6e2d-462c-a1e5-475e20ccafe3)

**Comment by rblcoder** [comment]
@nikki603 What is the authentication mode you are using? Is it basic authentication or something else?

**Comment by nikki603** [comment]
@rblcoder fine grain access control is enabled so I'm using IAM auth. I'm using AWS SSO locally. When running from a CI/CD pipeline I will be using the aws_access_key, aws_secret_key, and aws_token params.

**Comment by rblcoder** [comment]
@nikki603 I am able apply the following terraform code, I have defined a custom endpoint for my AWS OpenSearch Service domain.

```terraform {
  required_providers {
    opensearch = {
      source = "opensearch-project/opensearch"
      version = "2.2.0"
    }
  }
}

provider "opensearch" {
  url = "https://customsubdomain.domain.tld"
  healthcheck        = "false"
  aws_region          = "region"
  
  version_ping_timeout = "10"

}

resource "opensearch_index" "index" {
  name = "sample"
  number_of_replicas = "1"
  number_of_shards = "1"
}```

**Comment by rblcoder** [comment]
@nikki603 I also tested modifying an existing AWS OpenSearch domain and specifying a custom endpoint, it is working.

**Comment by nikki603** [comment]
I see that I was missing  `aws_region  = "region"` when using a custom domain. It works now. Thanks for the attention!

**Comment by rblcoder** [comment]
Great, good to hear it works now!
