### ISSUE TITLE
Release v2.2.1 OpenSearch Terraform Provider.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/terraform-provider-opensearch#172]
## Release v2.2.1
Prepare for the release of v2.2.1 by creating a corresponding tag, v2.2.1. Below are the commit details that will be included in this release: [link](https://github.com/opensearch-project/terraform-provider-opensearch/compare/v2.2.0...main).

**Comment by prudhvigodithi** [comment]
Adding @peterzhuamazon @jackson-theisen @phillbaker @rblcoder @bbarani

**Comment by rblcoder** [comment]
I am good with the release.

**Comment by prudhvigodithi** [comment]
OpenSearch Terraform Provider **v2.2.1** is released now. Thanks to all the contributors! :tada:
Terraform Provider Download link: https://registry.terraform.io/providers/opensearch-project/opensearch/2.2.1
Release Details: https://github.com/opensearch-project/terraform-provider-opensearch/releases/tag/v2.2.1
