### ISSUE TITLE
[BUG] With version 2.3.0 of the provider, the ressource opensearch_channel_configuration cannot be applied when assuming an iam role in the provider

### ISSUE THREAD

**Issue by Jaewongtongsoup** [opensearch-project/terraform-provider-opensearch#200]
### What is the bug?
With version 2.3.0 of the provider,  the ressource opensearch_channel_configuration cannot be applied when assuming an iam role in the provider like so : 
![image](https://github.com/opensearch-project/terraform-provider-opensearch/assets/98191464/39d680dd-3553-40e7-ba6d-876cdfd062ca)
![image](https://github.com/opensearch-project/terraform-provider-opensearch/assets/98191464/3e047f6f-7e07-47c3-bc03-5b9dec55d4ee)

### Do you have any screenshots?
![image](https://github.com/opensearch-project/terraform-provider-opensearch/assets/98191464/a57ac27d-8140-4b5f-aeea-8933265db717)
provider.terraform-provider-opensearch_v2.3.0: Response contains error diagnostic: diagnostic_severity=ERROR tf_proto_version=5.4 tf_provider_addr=provider tf_resource_type=opensearch_channel_configuration @module=sdk.proto diagnostic_detail= tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/internal/diag/diagnostics.go:58 diagnostic_summary="HTTP 403 Forbidden: Permission denied. Please ensure that the correct credentials are being used to access the cluster." tf_req_id=4c4f9019-ad7d-e488-f5e9-008d96464823 timestamp=2024-06-20T17:46:03.247Z

It works perfectly when I force version 2.2.0 of the provider.

 Other ressources that also uses this provider configs with version 2.3.0 doesnt seems to be affected and works perfectly like : 
![image](https://github.com/opensearch-project/terraform-provider-opensearch/assets/98191464/678203a3-5f83-454f-a974-a4b853f840bb)

**Comment by rblcoder** [comment]
The following terraform code works for me 

```
terraform {
  required_providers {
    opensearch = {
      source = "opensearch-project/opensearch"
      version = "2.3.0"
    }
  }
}

provider "opensearch" {
  url = "url"
  healthcheck        = "false"
  aws_region          = "region"
  aws_assume_role_arn = "assume role arn"
  aws_assume_role_external_id = "external id"
  version_ping_timeout = "10"

}

resource "opensearch_index" "index" {
  name = "sample"
  number_of_replicas = "1"
  number_of_shards = "1"
  
}

resource "opensearch_channel_configuration" "webhook_channel_configuration" {
  body = <<EOF
{
  "id": "sample-webhook-id",
  "name": "sample-name",
  "config": {
    "name": "Sample Webhook Channel",
    "description": "Sample webhook description",
    "config_type": "webhook",
    "is_enabled": true,
    "webhook": {
      "url": "https://www.example.com"
    }
  }
}
EOF
}

```

**Comment by Jaewongtongsoup** [comment]
Can you try using an AWS SNS channel instead of a webhook?

**Comment by rblcoder** [comment]
The following works for me

```
terraform {
  required_providers {
    opensearch = {
      source = "opensearch-project/opensearch"
      version = "2.3.0"
    }
  }
}

provider "opensearch" {
  url = "url"
  healthcheck        = "false"
  aws_region          = "region"
  aws_assume_role_arn = "role arn"
  aws_assume_role_external_id = "opensearch-external"
  version_ping_timeout = "10"

}

resource "opensearch_index" "index" {
  name = "sample"
  number_of_replicas = "1"
  number_of_shards = "1"
  
}

resource "opensearch_channel_configuration" "sns_channel_configuration" {
  body = <<EOF
{
  "id": "sample-sns-id",
  "name": "sample-name",
  "config": {
      "name": "sns-channel",  
      "config_type": "sns",  
        "sns": {  
          "topic_arn": "topic arn",  
          "role_arn": "role arn"  
        } 

      }
}
EOF
}

```

**Comment by prudhvigodithi** [comment]
Thanks @rblcoder, closing this issue @Jaewongtongsoup please feel-free to re-open if required.
