### ISSUE TITLE
[BUG] what is "registry.terraform.io/hashicorp/opens"

### ISSUE THREAD

**Issue by JAEJUNKIM1229** [opensearch-project/terraform-provider-opensearch#201]
### What is the bug?
When running terraform init, it discovers registry.terraform.io/hashicorp/opens, but I can't find this provider anywhere.

**Comment by rblcoder** [comment]
@JAEJUNKIM1229 Could you please share a complete sample Terraform code with the provider version and configuration?

**Comment by prudhvigodithi** [comment]
Hey @JAEJUNKIM1229 closing this issue, please feel free to re-open if you are still facing issues with `terraform init`. Thanks
