### ISSUE TITLE
[BUG] Intermittent checksum failures with provider break CI/CD pipelines

### ISSUE THREAD

**Issue by stantonk** [opensearch-project/terraform-provider-opensearch#204]
### What is the bug?
Terraform apply intermittently fails due to checksum mismatches with provider.

```
Initializing provider plugins...
- Reusing previous version of opensearch-project/opensearch from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file
- Reusing previous version of hashicorp/vault from the dependency lock file
- Using opensearch-project/opensearch v2.0.0 from the shared cache directory
- Using hashicorp/aws v3.72.0 from the shared cache directory
- Using hashicorp/vault v2.18.0 from the shared cache directory

Error: Failed to install provider from shared cache

Error while importing opensearch-project/opensearch v2.0.0 from the shared
cache directory: the provider cache at .terraform/providers has a copy of
registry.terraform.io/opensearch-project/opensearch 2.0.0 that doesn't match
any of the checksums recorded in the dependency lock file.
```

### How can one reproduce the bug?

It seems to happen intermittently.

### What is the expected behavior?

Checksums for providers should not fail.

### What is your host/environment?
Ubuntu 18.04.6 LTS, AWS EC2

**Comment by prudhvigodithi** [comment]
[Triage]
Hey @stantonk can you provide more details here regarding your CI/CD workflow anb are you using the latest version of the provider and running the `terraform init`?
Thank you

**Comment by prudhvigodithi** [comment]
Hey @stantonk closing this issue, please feel-free to re-open if you are still having issues.
Thank you 
@getsaurabh02 @rblcoder
