### ISSUE TITLE
[FEATURE] Add GPG key for use with OpenTofu's registry

### ISSUE THREAD

**Issue by bxn-ts** [opensearch-project/terraform-provider-opensearch#208]
### Is your feature request related to a problem?
OpenTofu is asking for support from the provider authors, in this case it's submitting a GPG key. This is supposed to help with securing the OpenTofu ecosystem even further. Details on how to do this can be found as part of the recent 1.8.0 release announcement: **[https://opentofu.org/blog/opentofu-1-8-0/#an-ask-for-help-gpg-keys-for-providers](https://opentofu.org/blog/opentofu-1-8-0/#an-ask-for-help-gpg-keys-for-providers)**

### What solution would you like?
The provider's GPG key is submitted to OpenTofu (via GitHub issue; instructions are mentioned above when following the link).

### What alternatives have you considered?
None.

### Do you have any additional context?
```
$ tofu init

Initializing the backend...

Initializing provider plugins...
- Finding opensearch-project/opensearch versions matching "2.3.0"...
- Installing opensearch-project/opensearch v2.3.0...
- Installed opensearch-project/opensearch v2.3.0. Signature validation was skipped due to the registry not containing GPG keys for this provider
```

**Comment by prudhvigodithi** [comment]
@bxn-ts closing this as the GPG key is added https://github.com/opensearch-project/terraform-provider-opensearch/issues/221#issuecomment-2479578888. Please take a look.
Thank you
