### ISSUE TITLE
[FEATURE] Configure Cluster Search Request Slow Logs

### ISSUE THREAD

**Issue by ironf1st** [opensearch-project/terraform-provider-opensearch#209]
### Is your feature request related to a problem?
As of [2.12](https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/logs/#search-request-slow-logs), we can configure cluster level search request slow logs. There is no support for this in the provider right now.

### What solution would you like?
Add a block to `opensearch_cluster_settings` for search request slow logs:

```hcl
resource "opensearch_cluster_settings" "example" {
search_request_slow_logs {
    slowlog_level = "TRACE"
    slowlog_threshold_warn = "10s"
    slowlog_threshold_info = "5s"
    slowlog_threshold_debug = "2s"
    slowlog_threshold_trace = "10ms"
}

```
### What alternatives have you considered?
I do not see an alternative method using this provider. The only other way to achieve this via Terraform is via a script and the external provider, the local-exec provider running a PUT to the cluster, or via the http provider.

### Do you have any additional context?
This is a relatively new feature that is by default disabled in the cluster, set to -1.

**Comment by prudhvigodithi** [comment]
Hey @ironf1st something like the following should be even easier for the user.

```
resource "opensearch_cluster_settings" "slowlog" {
  cluster_max_shards_per_node = 10
  cluster_search_request_slowlog_level            = "WARN"
  cluster_search_request_slowlog_threshold_warn   = "10s"
  cluster_search_request_slowlog_threshold_info   = "5s"
  cluster_search_request_slowlog_threshold_debug  = "2s"
  cluster_search_request_slowlog_threshold_trace  = "100ms"
}
```

I have a PR open https://github.com/opensearch-project/terraform-provider-opensearch/pull/211 to support the Cluster Search Request Slow Logs.

Thanks
@getsaurabh02 @peterzhuamazon @rblcoder

**Comment by prudhvigodithi** [comment]
The terraform provider [2.3.1](https://registry.terraform.io/providers/opensearch-project/opensearch/2.3.1) is released supporting Search Request Slow Logs, @ironf1st please take a look.
Thanks

**Comment by prudhvigodithi** [comment]
Closing this issue since the terraform provider [2.3.1](https://registry.terraform.io/providers/opensearch-project/opensearch/2.3.1) is released with Cluster Search Request Slow Logs support, please feel free to add a comment or re-open if required.
Thank you
@getsaurabh02
