### ISSUE TITLE
[BUG] Expired signing key

### ISSUE THREAD

**Issue by ghost** [opensearch-project/terraform-provider-opensearch#222]
### What is the bug?

The GPG signing key for this provider expired in February. Using an expired signing key may cause signatures to be rejected as the signature verification in OpenTofu/Terraform develops.

### How can one reproduce the bug?

Import the key submitted in opentofu/registry#1296, which matches your latest release, into GPG and list the keys.

### What is the expected behavior?

The releases should be signed with a non-expired key.

### What is your host/environment?

N/A

### Do you have any screenshots?

![image](https://github.com/user-attachments/assets/67de1ebe-07e7-4b44-8f6c-e399bf01c226)

### Do you have any additional context?

https://github.com/opentofu/registry/issues/1296
https://github.com/opensearch-project/terraform-provider-opensearch/issues/221

**Comment by prudhvigodithi** [comment]
I see whats happening, the key was renewed by was not submitted to the hashicorp gpg-keys keys, hence `curl 'https://registry.terraform.io/v1/providers/opensearch-project/opensearch/2.3.1/download/linux/amd64' | jq --raw-output '.signing_keys | .gpg_public_keys | .[0] | .ascii_armor'` shows old key.

**Comment by prudhvigodithi** [comment]
Hey @abstractionfactory I have updated the public key in https://github.com/opentofu/registry/issues/1296.
Thank you
