### ISSUE TITLE
[FEATURE] Support notifications

### ISSUE THREAD

**Issue by moritzzimmer** [opensearch-project/terraform-provider-opensearch#30]
### Is your feature request related to a problem?

Opensearch destinations seem to be deprecated with 2.0 and have been superseded by notifications, see https://opensearch.org/docs/latest/observing-your-data/alerting/monitors/#questions-about-destinations and https://docs.aws.amazon.com/opensearch-service/latest/developerguide/alerting.html#alerting-notifications.

Using a `opensearch_destination` ressource with this provider and a Opensearch domain 2.x fails with

```
│ Error: elastic: Error 405 (Method Not Allowed)
```

### What solution would you like?

Support the notifications API in this provider: https://opensearch.org/docs/latest/observing-your-data/notifications/api/

### What alternatives have you considered?

Create notifications using direct API calls or using the Dashboards UI.

### Do you have any additional context?

no

**Comment by gaiksaya** [comment]
[Triage] Hi @opensearch-project/alerting-plugin , @opensearch-project/notifications Can you look into this issue?

**Comment by prudhvigodithi** [comment]
Hey @moritzzimmer thanks for the details, I believe at this point the provider is battle tested for `1.x` versions, @phillbaker can you please add more details for `2.x`?
Thanks you
