### ISSUE TITLE
[BUG] Update to use _plugin in request paths

### ISSUE THREAD

**Issue by DagW** [opensearch-project/terraform-provider-opensearch#32]
### What is the bug?
_A clear and concise description of the bug._
I get the response:
"Your request: '/_opendistro' is not allowed."

when creating a role. It seems to be because the provider uses `_opendistro` instead of `_plugin` in the path.

This is using a Opensearch cluster created with the AWS Opensearch service, version 2.5.0

### How can one reproduce the bug?
_Steps to reproduce the behavior._

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

Expected the role to be created.

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by rishabh6788** [comment]
@DagW OS 2.x is still not fully supported and we have a [PR](https://github.com/opensearch-project/terraform-provider-opensearch/pull/16) to fully support it.

**Comment by prudhvigodithi** [comment]
Hey @DagW, please use the latest provider, the 2.x support has been added.
https://registry.terraform.io/providers/opensearch-project/opensearch/2.0.0-beta.1
Closing this issue, please feel-free to re-open if required.
Related 2.x support PR: https://github.com/opensearch-project/terraform-provider-opensearch/pull/62
Thank you 
Adding @phillbaker @bbarani @peterzhuamazon
