### ISSUE TITLE
[BUG] tenant allowed_actions not working on opensearch_role

### ISSUE THREAD

**Issue by pawelwasowski** [opensearch-project/terraform-provider-opensearch#38]
### What is the bug?
_I want to create role with read access to all tenants._

```
resource "opensearch_role" "global_read_only" {
  role_name           = "global_read_only"
  description         = "Read only access to global tenants and indexes"
  cluster_permissions = ["read", "get", "search"]
  index_permissions {
    index_patterns  = ["*"]
    allowed_actions = ["read", "get", "opensearch_dashboards_all_read", "search"]
  }
  tenant_permissions {
    tenant_patterns = ["*"]
    allowed_actions = ["read"]
  }
}

```

_After terraform apply I can see that read/write permission property is empty in OpenSearch console_. 

_I am using AWS OpenSearch v 1.3._

**Comment by jmurillo9** [comment]
@pawelwasowski & @rishabh6788 - I ran into a similar issue before. I'm using OpenSearch 2.9. You need to do `allowed_actions = ["kibana_all_write"]`.

This will apply `Read and Write` as seen within the UI. 

Hope this helps!.

**Comment by pawelwasowski** [comment]
thans @jmurillo9 
it works!
