### ISSUE TITLE
[FEATURE] Support 2.x version of OpenSearch

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/terraform-provider-opensearch#39]
### Is your feature request related to a problem?
Existing [release](https://registry.terraform.io/providers/opensearch-project/opensearch/latest) of the terraform provider does only support 1.x version of OpenSearch. Allow the same provider to support 2.x series of OpenSearch as well.

### What solution would you like?
Support the provider to be compatible with 2.x series of OpenSearch.
Sample PR: https://github.com/opensearch-project/terraform-provider-opensearch/pull/16
Have a separate PR with unit tests for features/changes that support 2.x series of OpenSearch while still supporting 1.x series.

**Comment by rishabhToshniwal** [comment]
Team,

When can we expect 2.X support ?

**Comment by phillbaker** [comment]
See https://github.com/opensearch-project/OpenSearch/issues/2480 for breaking changes

**Comment by bbarani** [comment]
Released [beta](https://registry.terraform.io/providers/opensearch-project/opensearch/2.0.0-beta.1) version of provider to support 2.x versions.

**Comment by prudhvigodithi** [comment]
Released the non beta version of provider that support 2.x version of OpenSearch 
https://registry.terraform.io/providers/opensearch-project/opensearch/2.0.0
Closing this issue, users please open a new issue for enhancement or bugs related to the functionality of the provider.
Thank you 
@phillbaker @bbarani @peterzhuamazon @jackson-theisen
