### ISSUE TITLE
[FEATURE] Alias resource type

### ISSUE THREAD

**Issue by arichtman-srt** [opensearch-project/terraform-provider-opensearch#55]
### Is your feature request related to a problem?

I'm unable to create all the necessary objects by way of Terraform.
Aliases, which are essential to using dynamic indexes and rollovers, are not present in the provider.

### What solution would you like?

A resource type `opensearch_alias` that operates about the same as everything else in the provider.

### What alternatives have you considered?

Combination of `local_file` with `jsonencode` and `null` resource of `local_script` to manually `curl` the API.

### Do you have any additional context?

https://opensearch.org/docs/1.3/im-plugin/index-alias/

**Comment by prudhvigodithi** [comment]
[Untriage]
Hey @arichtman-srt I see the limitation not possible to add alias via this provider, can you take a look and contribute this alias setting to the provider?
Thank you

**Comment by arichtman-srt** [comment]
I'd love to but I don't know GoLang at all 😔 
I was able to add some via the JSON body payload in the end, so it's not blocking for me anymore.
Thanks for your time!

**Comment by yoicomment** [comment]
> I'd love to but I don't know GoLang at all 😔 I was able to add some via the JSON body payload in the end, so it's not blocking for me anymore. Thanks for your time!

How to create an alias via the JSON body payload? How does that work?

**Comment by prudhvigodithi** [comment]
Hey @arichtman-srt can you please post you alternate approach that worked? It would be helpful for the community.
Thank you

**Comment by arichtman-srt** [comment]
https://github.com/arichtman/terraform-opensearch-resources/blob/main/main.tf

**Comment by yoicomment** [comment]
@arichtman-srt thank you honey

**Comment by yoicomment** [comment]
Is it possible to configure AD/LDAP via terraform provider for opensearch?

**Comment by prudhvigodithi** [comment]
Hey @yoicomment since this issue is closed and with your topic AD/LDAP can you please open a new issue with some detailed description on what is the requirement?
Thank you

**Comment by yoicomment** [comment]
@prudhvigodithi ok darling, will do
