### ISSUE TITLE
[BUG] opensearch_cluster_settings action_auto_create_index validation is inaccurate

### ISSUE THREAD

**Issue by arichtman-srt** [opensearch-project/terraform-provider-opensearch#58]
### What is the bug?

Resource `opensearch_cluster_settings` property `action_auto_create_index` fails validation for legitimate string values.

### How can one reproduce the bug?

1. Create resource block of type `opensearch_cluster_settings`
2. Set `action_auto_create_index` to `-.aws_cold_catalog*,+*`
3. Terraform apply

### What is the expected behavior?

String should pass validation and Terraform should apply

### What is your host/environment?

```zsh
$ uname -a && terraform -version
Darwin bne-nb-ariel 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:21:34 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8112 arm64 arm Darwin
Terraform v1.5.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.62.0
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/opensearch-project/opensearch v1.0.0
+ provider registry.terraform.io/phillbaker/elasticsearch v2.0.4
```

### Do you have any screenshots?

![image](https://github.com/opensearch-project/terraform-provider-opensearch/assets/121832558/3a9bf4d7-bf43-4983-b1bb-9aa531bfb4b9)

![image](https://github.com/opensearch-project/terraform-provider-opensearch/assets/121832558/267ecce6-90c2-4fb9-b386-b82338c1f1d6)

### Do you have any additional context?

Perhaps the variable should be either `bool` or `list(string)` instead?

**Comment by prudhvigodithi** [comment]
[Untriage]
Hey @arichtman-srt just curious did you add in double quotes `"-.aws_cold_catalog*,+*"`, https://github.com/opensearch-project/terraform-provider-opensearch/blob/main/docs/resources/cluster_settings.md?plain=1#L18.

**Comment by arichtman-srt** [comment]
Yes, it has quotes

![image](https://github.com/opensearch-project/terraform-provider-opensearch/assets/121832558/c012b4d2-dffe-4b4b-844c-ec69a19726ce)

**Comment by prudhvigodithi** [comment]
Hey @arichtman-srt I have created a PR https://github.com/opensearch-project/terraform-provider-opensearch/pull/79 to relax the index patterns, I have tested with pattern `-.aws_cold_catalog*,+*` and works fine. Thanks
Adding @phillbaker @bbarani @peterzhuamazon

**Comment by prudhvigodithi** [comment]
Closing this issue as the PR https://github.com/opensearch-project/terraform-provider-opensearch/pull/79 related to fix is merged and released https://registry.terraform.io/providers/opensearch-project/opensearch/2.0.0. @arichtman-srt please feel free to re-open if required
Thank you
