### ISSUE TITLE
[BUG] opensearch_cluster_settings unable to apply cluster_max_shards_per_node

### ISSUE THREAD

**Issue by arichtman-srt** [opensearch-project/terraform-provider-opensearch#59]
### What is the bug?

`opensearch_cluster_settings` unable to apply `cluster_max_shards_per_node`

### How can one reproduce the bug?

![image](https://github.com/opensearch-project/terraform-provider-opensearch/assets/121832558/ef0edfed-8706-44d4-b750-feb9992c303b)

### What is the expected behavior?

Terraform is able to apply the changes, cluster query show the updated value.

### What is your host/environment?

```zsh
$ uname -a && terraform -version
Darwin bne-nb-ariel 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:21:34 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8112 arm64 arm Darwin
Terraform v1.5.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.62.0
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/opensearch-project/opensearch v1.0.0
+ provider registry.terraform.io/phillbaker/elasticsearch v2.0.4
```

### Do you have any screenshots?

All using the same user as the Terraform provider configuration

1. Query the cluster for max shards
2. Inspect the json payload file
3. Send the request
4. Query the cluster for max shards to confirm

![image](https://github.com/opensearch-project/terraform-provider-opensearch/assets/121832558/13ca3d2f-1f64-49c3-8a53-6dd73e36545c)

**Comment by prudhvigodithi** [comment]
[Untriage]
Hey @arichtman-srt, from your screenshot it was changed from 1000 to 1001, so you are trying to change to 999?
AFAIK OpenSearch rejects any request that creates more shards than this limit allows, can you confirm if this is coming from OpenSearch or actual issue with the provider? Adding @phillbaker @bbarani

**Comment by arichtman-srt** [comment]
I'm unable to replicate the error
