### ISSUE TITLE
[BUG] opensearch_index resource does not seem to store imported mappings properly

### ISSUE THREAD

**Issue by david-alpert-nl** [opensearch-project/terraform-provider-opensearch#71]
### What is the bug?
The `opensearch_index` resource does not seem to store or manage the `mappings` property.

### How can one reproduce the bug?
1. Define an `opensearch` provider with valid connection (e.g. url, credentials, etc) to an existing OpenSearch server with a valid index containing mappings.
2. Define an `opensearch_index` resource with a mapping
3. Import the remote resource into terraform
4. Run a plan

### What is the expected behavior?
- A diff appears that includes the diff between remote mapping values of the imported index and the mappings JSON in the locally written terraform resource.
- Viewing terraform state for that resource would include the mapping JSON.

### What is the actual behavior?
- The plan says that the remote index needs to be recreated and shows the locally written mappings as a net add, as if the remote mapping was not stored during an import.
- Viewing terraform state (and provider logs) suggests that the OpenSearch client's response does not include the mappings. 

### What is your host/environment?
- macOS Monterey Version 12.6 [Apple M1 Max chip]

### Do you have any additional context?
- plans for mappings which were created by terraform seem to include the mapping in the diff as expected, suggesting that this mapping data is managed correctly when creating an index but is missing from the import results.
- viewing terraform state for a remote resource _created_ by this provider _does_ include the mapping JSON
- viewing terraform state for a remote resource _imported_ by this provider _does not_ include the mapping JSON

**Comment by david-alpert-nl** [comment]
from what I can tell I think this `resourceOpensearchIndexRead(...)` method is missing the mappings on import as it never explicitly gets them from the opensearch client:
https://github.com/opensearch-project/terraform-provider-opensearch/blob/08ca809a1111164e3d8a2fa2d3bfd1ea11700a29/provider/resource_opensearch_index.go#L701-L765

the [`osClient.IndexGetSettings`](https://github.com/opensearch-project/terraform-provider-opensearch/blob/08ca809a1111164e3d8a2fa2d3bfd1ea11700a29/provider/resource_opensearch_index.go#L717) call [uses the `/{index}/_settings` endpoint](https://github.com/olivere/elastic/blob/release-branch.v7/indices_get_settings.go#L150-L161) which does not return mappings, for example:
```json
{
  "my-index": {
    "settings": {
      "index": {
        "creation_date": "1692630469965",
        "number_of_shards": "5",
        "number_of_replicas": "1",
        "uuid": "M6a4_T9QSJ-EkydkCouCAg",
        "version": {
          "created": "136267827"
        },
        "provided_name": "my-index"
      }
    }
  }
}
```

I think the provider `read` method also needs to call the `osClient.GetMapping(index)` method which [uses the`/{index}/_mapping/` endpoint](https://github.com/olivere/elastic/blob/29ee98974cf1984dfecf53ef772d721fb97cb0b9/indices_get_mapping.go#L152-L155) to import the existing mapping.
```json
{
  "my-index": {
    "mappings": {
      "properties": {
           ...
      }
    }
  }
}
```

If I am on the right track I am happy to submit a pull request.

**Comment by david-alpert-nl** [comment]
I wonder now if this is an issue with API differences?

it appears that OpenSearch 2.9 exposes a more complete response at the `GET /{index}` endpoint that includes both mappings and settings, perhaps shaped more like this provider code expects 🤔

**Comment by jordarlu** [comment]
@david-alpert-nl , thanks for reporting the issue and share the finding ,,, would you mind also create a Pull Request for the team here to review and discuss ? thanks again !

**Comment by prudhvigodithi** [comment]
Thanks @david-alpert-nl, to the provider `Read` operation we should be adding a condition [osClient.GetMapping(index) method](https://github.com/olivere/elastic/blob/29ee98974cf1984dfecf53ef772d721fb97cb0b9/client.go#L1889C18-L1891), please open a pull request when you are ready, Thanks
Adding @phillbaker @bbarani @peterzhuamazon 
Thank you
