### ISSUE TITLE
[BUG] Opensearch index template creation fails via terraform

### ISSUE THREAD

**Issue by pastibog** [opensearch-project/terraform-provider-opensearch#72]
### What is the bug?
Attempting to create an index template via terraform results in an [type=x_content_parse_exception]. The resource definition is the exact one taken from here: https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/index_template

### How can one reproduce the bug?
Terraform file:
```
terraform {
  required_providers {
    opensearch = {
      source = "opensearch-project/opensearch"
      version = "2.0.0-beta.1"
    }
  }
}
resource "opensearch_index_template" "template_1" {
  name = "template_1"
  body = <<EOF
{
  "template": "te*",
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "type1": {
      "_source": {
        "enabled": false
      },
      "properties": {
        "host_name": {
          "type": "keyword"
        },
        "created_at": {
          "type": "date",
          "format": "EEE MMM dd HH:mm:ss Z YYYY"
        }
      }
    }
  }
}
EOF
}
```
Nothing has been changed in the resource definition, it is the exact one from the provider page.

### What is the expected behavior?
The index template is created.

### What is your host/environment?
AWS OpenSearch 2.7 domain
Terraform v1.4.5
opensearch-project/opensearch 2.0.0-beta.1

**Comment by jordarlu** [comment]
cc : @phillbaker , and @prudhvigodithi ... if you guys can help take a look . thanks!!

**Comment by huziahmetovsv** [comment]
Same for me:
Onprem OpenSearch 2.9.0
Terraform v1.5.7
opensearch-project/opensearch 2.0.0-beta.1

**Comment by pastibog** [comment]
Thanks, will try this.

**Comment by prudhvigodithi** [comment]
Thanks for the confirmation @huziahmetovsv, closing this issue, @pastibog @huziahmetovsv please feel free re-open if required.
Thank you
