### ISSUE TITLE
[FEATURE] Support KNN Index Setup

### ISSUE THREAD

**Issue by sam-h-bean** [opensearch-project/terraform-provider-opensearch#75]
### Is your feature request related to a problem?
I want to provision and configure KNN index properties via terraform but you don't seem to support the args that are added via plugin [here](https://opensearch.org/docs/latest/search-plugins/knn/approximate-knn/)

### What solution would you like?
Support configuring KNN index properties via terraform.

### What alternatives have you considered?
Use a script that runs after terraform to apply additional index configuration.

### Do you have any additional context?
No

**Comment by prudhvigodithi** [comment]
[Untriage]
Thanks @sam-h-bean 
@rblcoder @afrodidact @premkirank please take a look.
Thank you

**Comment by prudhvigodithi** [comment]
Thanks @mcarroll1.
