### ISSUE TITLE
[FEATURE] Allow tenant selection when creating Dashboard Objects

### ISSUE THREAD

**Issue by spacez320** [opensearch-project/terraform-provider-opensearch#97]
### Is your feature request related to a problem?
[The Dashboard Object spec](https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/dashboard_object) provides a nice way to inject index patterns/visualizations/dashboards, but it seems like it's only able to provide these resources to the global tenant.

### What solution would you like?
Specifying the tenant to target for the Dashboard Object. Possibly other resources?

E.g.

```
resource "opensearch_dashboard_object" "test_index_pattern_v7" {
  body = <<EOF
[
  {
    "_id": "index-pattern:cloudwatch",
    "_type": "doc",
    "_source": {
      "type": "index-pattern",
      "index-pattern": {
        "title": "cloudwatch-*",
        "timeFieldName": "timestamp"
      }
    }
  }
]
EOF
  security_tenant = "my_tenant"  # Add this.
}
```

### What alternatives have you considered?
It seems like you can generally specify tenancy in direct API calls by doing something like providing `security_tenant=<something>` as a URL parameter. For now probably going to invoke the API directly to copy dashboard objects around, but it would be nice if `security_tenant` was an option on the resource, or the provider instantiation, or something.

### Do you have any additional context?
Sorry if I'm missing something!

**Comment by peterzhuamazon** [comment]
Similar to:
* https://github.com/opensearch-project/terraform-provider-opensearch/issues/104

**Comment by spacez320** [comment]
@peterzhuamazon It looks like https://github.com/opensearch-project/terraform-provider-opensearch/issues/104 does cover this request. Happy to have this be closed and follow that, instead.
